import { FILE_HEADER } from './emit_helpers';
import { collectionDir } from './controller';
import type { PreparedCollection } from './prepare';

// Emit the public barrel `lib/design_system.dart`.

export function emitBarrel(
  collections: PreparedCollection[],
  hasComposites: { paintStyles: boolean; effectStyles: boolean; textStyles: boolean },
): string {
  let out = `/// Design system package — generated by Varcast.\n`;
  out += `/// Do not edit by hand.\n`;
  out += `library design_system;\n\n`;
  out += `${FILE_HEADER}`;
  out += `export 'src/wrapper.dart' show DesignSystemWrapper;\n`;
  out += `export 'src/design_system.dart' show DesignSystem;\n`;
  out += `export 'src/theme.dart' show AppTheme;\n\n`;

  for (const col of collections) {
    const file = `src/${collectionDir(col)}/${col.fileBaseName}.dart`;
    out += `export '${file}' show ${col.className}, ${col.className}Mode;\n`;
  }
  out += `\n`;

  if (hasComposites.paintStyles)
    out += `export 'src/composites/color_styles.dart' show DSColorStyles;\n`;
  if (hasComposites.effectStyles)
    out += `export 'src/composites/shadows.dart' show DSShadow, DSShadows;\n`;
  if (hasComposites.textStyles)
    out += `export 'src/composites/text_styles.dart' show DSStyles, DSTextStyle;\n`;

  return out;
}

