import type { ManifestDiff } from '../../../manifest';

export function generateChangelog(diff: ManifestDiff): string {
  const lines: string[] = [];
  lines.push('# Changelog');
  lines.push('');
  lines.push('Generated by Varcast. Do not edit by hand.');
  lines.push('');

  if (
    diff.added.length === 0 &&
    diff.removed.length === 0 &&
    diff.renamed.length === 0
  ) {
    lines.push('No changes.');
    return lines.join('\n');
  }

  if (diff.added.length > 0) {
    lines.push('## Added');
    for (const a of diff.added) {
      lines.push(`- \`${a.name}\`${a.figmaName ? ` — ${a.figmaName}` : ''}`);
    }
    lines.push('');
  }

  if (diff.removed.length > 0) {
    lines.push('## Removed');
    for (const r of diff.removed) {
      lines.push(`- \`${r.name}\`${r.figmaName ? ` — ${r.figmaName}` : ''}`);
    }
    lines.push('');
  }

  if (diff.renamed.length > 0) {
    lines.push('## Renamed (Figma only; stable name unchanged)');
    for (const r of diff.renamed) {
      lines.push(`- \`${r.name}\`: \`${r.oldFigmaName}\` → \`${r.newFigmaName}\``);
    }
    lines.push('');
  }

  return lines.join('\n').trimEnd();
}

