import type { RGBA } from '../../../ir/types';

export const FILE_HEADER = `// GENERATED FILE — do not edit by hand.
// Generated by Figma → Flutter Design System Plugin.

`;

// ── Number / color literal formatting ─────────────────────────────────────

export function rgbaToHex(rgba: RGBA): string {
  const hex = (v: number) =>
    Math.round(clamp01(v) * 255)
      .toString(16)
      .padStart(2, '0')
      .toUpperCase();
  return `0x${hex(rgba.a)}${hex(rgba.r)}${hex(rgba.g)}${hex(rgba.b)}`;
}

export function colorLiteral(rgba: RGBA): string {
  return `const Color(${rgbaToHex(rgba)})`;
}

// Doubles round to 6 decimals (matches Phase 3 float-noise rule) then trim
// trailing zeros. Integers always emit with `.0` so Dart treats them as double.
export function doubleLiteral(n: number): string {
  if (!Number.isFinite(n)) return '0.0';
  if (Number.isInteger(n)) return `${n}.0`;
  const fixed = (Math.round(n * 1e6) / 1e6).toFixed(6);
  return fixed.replace(/0+$/, '').replace(/\.$/, '.0');
}

export function stringLiteral(s: string): string {
  return `'${s.replace(/\\/g, '\\\\').replace(/'/g, "\\'")}'`;
}

export function boolLiteral(b: boolean): string {
  return b ? 'true' : 'false';
}

function clamp01(n: number): number {
  return n < 0 ? 0 : n > 1 ? 1 : n;
}

// ── Indent helpers ─────────────────────────────────────────────────────────

export function indent(s: string, n = 2): string {
  const pad = ' '.repeat(n);
  return s
    .split('\n')
    .map((line) => (line.length === 0 ? line : pad + line))
    .join('\n');
}

// ── Linear gradient angle → Alignment pair (pre-computed at emit time) ─────

export function angleToAlignmentDart(radians: number): {
  begin: string;
  end: string;
} {
  const round = (v: number) => {
    const r = Math.round(v * 1e6) / 1e6;
    return r === 0 ? 0 : r;
  };
  const sin = round(Math.sin(radians));
  const cos = round(Math.cos(radians));
  return {
    begin: `Alignment(${doubleLiteral(-sin)}, ${doubleLiteral(-cos)})`,
    end: `Alignment(${doubleLiteral(sin)}, ${doubleLiteral(cos)})`,
  };
}

